### PR TITLE
fix checksum handling in send_read()

### PR DESCRIPTION
**Pull request by martinayotte**
I think this should fix the issue https://github.com/merbanan/rfid_app/issues/7

### CODE REVIEW

**Comment by merbanan** [comment]
Did you test this? Can you show the command line output before and after?

**Comment by martinayotte** [comment]
Of course I did tested it ... In my local version, I've added few more printf() to prove that checksum is properly calculated ...

As mentioned in issue #7, I've said : 

Obsiously, the CRC verify isn't correct, it is calculated on empty buffer, therefore always zero.

https://github.com/merbanan/rfid_app/blob/master/rfid_app.c#L130-L134

also result comparision is done with the wrong bytes, against c[cnt-1], while printf is done with c[cnt] :

https://github.com/merbanan/rfid_app/blob/master/rfid_app.c#L146-L147

**Comment by merbanan** [comment]
Thank you

**Comment by martinayotte** [comment]
Welcome !

**Pull request merged**
